CREATE OR REPLACE VIEW SBR_TBL_DATAPUMP AS 
SELECT TABLE_NAME
  FROM DBA_TABLES
 WHERE (TABLE_NAME LIKE 'SBR%'
    OR TABLE_NAME LIKE 'OCN%'
    OR TABLE_NAME LIKE 'SGN%'
    OR TABLE_NAME LIKE 'INTERACAO%'
    OR TABLE_NAME LIKE 'CRS%'
    OR TABLE_NAME LIKE 'CRW%'
    OR TABLE_NAME LIKE 'CRQ%'
    OR TABLE_NAME LIKE 'ECM%'
    OR TABLE_NAME LIKE 'CRM%'
    OR TABLE_NAME LIKE 'SZ%')
    AND TABLE_NAME NOT LIKE 'OCN_LOG_ENTIDADE_CAMPO'
    AND OWNER = 'SIGA'
 ORDER BY NUM_ROWS DESC;
 
SELECT *
  FROM SBR_TBL_DATAPUMP;
  
  
  
  
  
  
  
  
  
 